
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */


#ifndef __GPIODGLIB_GENERATED_ENUMS_H__
#define __GPIODGLIB_GENERATED_ENUMS_H__

#if !defined (__GPIODGLIB_INSIDE__)
#error "Only <gpiod-glib.h> can be included directly."
#endif

G_BEGIN_DECLS

GType gpiodglib_edge_event_type_get_type(void) G_GNUC_CONST;
#define GPIODGLIB_EDGE_EVENT_TYPE_TYPE (gpiodglib_edge_event_type_get_type())

GType gpiodglib_info_event_type_get_type(void) G_GNUC_CONST;
#define GPIODGLIB_INFO_EVENT_TYPE_TYPE (gpiodglib_info_event_type_get_type())

GType gpiodglib_line_value_get_type(void) G_GNUC_CONST;
#define GPIODGLIB_LINE_VALUE_TYPE (gpiodglib_line_value_get_type())
GType gpiodglib_line_direction_get_type(void) G_GNUC_CONST;
#define GPIODGLIB_LINE_DIRECTION_TYPE (gpiodglib_line_direction_get_type())
GType gpiodglib_line_edge_get_type(void) G_GNUC_CONST;
#define GPIODGLIB_LINE_EDGE_TYPE (gpiodglib_line_edge_get_type())
GType gpiodglib_line_bias_get_type(void) G_GNUC_CONST;
#define GPIODGLIB_LINE_BIAS_TYPE (gpiodglib_line_bias_get_type())
GType gpiodglib_line_drive_get_type(void) G_GNUC_CONST;
#define GPIODGLIB_LINE_DRIVE_TYPE (gpiodglib_line_drive_get_type())
GType gpiodglib_line_clock_get_type(void) G_GNUC_CONST;
#define GPIODGLIB_LINE_CLOCK_TYPE (gpiodglib_line_clock_get_type())

G_END_DECLS

#endif /* __GPIODGLIB_GENERATED_ENUMS_H__ */

/* Generated data ends here */

