
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */


#include <gpiodglib.h>

/* enumerations from "edge-event.h" */

GType gpiodglib_edge_event_type_get_type(void)
{
	static gsize static_g_enum_type_id;

	if (g_once_init_enter(&static_g_enum_type_id)) {
		static const GEnumValue values[] = {
			{GPIODGLIB_EDGE_EVENT_RISING_EDGE, "GPIODGLIB_EDGE_EVENT_RISING_EDGE", "rising-edge"},
			{GPIODGLIB_EDGE_EVENT_FALLING_EDGE, "GPIODGLIB_EDGE_EVENT_FALLING_EDGE", "falling-edge"},
			{ 0, NULL, NULL }
		};

		GType g_enum_type_id = g_enum_register_static(
				g_intern_static_string("GpiodglibEdgeEventType"), values);

		g_once_init_leave (&static_g_enum_type_id, g_enum_type_id);
	}

	return static_g_enum_type_id;
}

/* enumerations from "info-event.h" */

GType gpiodglib_info_event_type_get_type(void)
{
	static gsize static_g_enum_type_id;

	if (g_once_init_enter(&static_g_enum_type_id)) {
		static const GEnumValue values[] = {
			{GPIODGLIB_INFO_EVENT_LINE_REQUESTED, "GPIODGLIB_INFO_EVENT_LINE_REQUESTED", "requested"},
			{GPIODGLIB_INFO_EVENT_LINE_RELEASED, "GPIODGLIB_INFO_EVENT_LINE_RELEASED", "released"},
			{GPIODGLIB_INFO_EVENT_LINE_CONFIG_CHANGED, "GPIODGLIB_INFO_EVENT_LINE_CONFIG_CHANGED", "config-changed"},
			{ 0, NULL, NULL }
		};

		GType g_enum_type_id = g_enum_register_static(
				g_intern_static_string("GpiodglibInfoEventType"), values);

		g_once_init_leave (&static_g_enum_type_id, g_enum_type_id);
	}

	return static_g_enum_type_id;
}

/* enumerations from "line.h" */

GType gpiodglib_line_value_get_type(void)
{
	static gsize static_g_enum_type_id;

	if (g_once_init_enter(&static_g_enum_type_id)) {
		static const GEnumValue values[] = {
			{GPIODGLIB_LINE_VALUE_INACTIVE, "GPIODGLIB_LINE_VALUE_INACTIVE", "inactive"},
			{GPIODGLIB_LINE_VALUE_ACTIVE, "GPIODGLIB_LINE_VALUE_ACTIVE", "active"},
			{ 0, NULL, NULL }
		};

		GType g_enum_type_id = g_enum_register_static(
				g_intern_static_string("GpiodglibLineValue"), values);

		g_once_init_leave (&static_g_enum_type_id, g_enum_type_id);
	}

	return static_g_enum_type_id;
}

GType gpiodglib_line_direction_get_type(void)
{
	static gsize static_g_enum_type_id;

	if (g_once_init_enter(&static_g_enum_type_id)) {
		static const GEnumValue values[] = {
			{GPIODGLIB_LINE_DIRECTION_AS_IS, "GPIODGLIB_LINE_DIRECTION_AS_IS", "as-is"},
			{GPIODGLIB_LINE_DIRECTION_INPUT, "GPIODGLIB_LINE_DIRECTION_INPUT", "input"},
			{GPIODGLIB_LINE_DIRECTION_OUTPUT, "GPIODGLIB_LINE_DIRECTION_OUTPUT", "output"},
			{ 0, NULL, NULL }
		};

		GType g_enum_type_id = g_enum_register_static(
				g_intern_static_string("GpiodglibLineDirection"), values);

		g_once_init_leave (&static_g_enum_type_id, g_enum_type_id);
	}

	return static_g_enum_type_id;
}

GType gpiodglib_line_edge_get_type(void)
{
	static gsize static_g_enum_type_id;

	if (g_once_init_enter(&static_g_enum_type_id)) {
		static const GEnumValue values[] = {
			{GPIODGLIB_LINE_EDGE_NONE, "GPIODGLIB_LINE_EDGE_NONE", "none"},
			{GPIODGLIB_LINE_EDGE_RISING, "GPIODGLIB_LINE_EDGE_RISING", "rising"},
			{GPIODGLIB_LINE_EDGE_FALLING, "GPIODGLIB_LINE_EDGE_FALLING", "falling"},
			{GPIODGLIB_LINE_EDGE_BOTH, "GPIODGLIB_LINE_EDGE_BOTH", "both"},
			{ 0, NULL, NULL }
		};

		GType g_enum_type_id = g_enum_register_static(
				g_intern_static_string("GpiodglibLineEdge"), values);

		g_once_init_leave (&static_g_enum_type_id, g_enum_type_id);
	}

	return static_g_enum_type_id;
}

GType gpiodglib_line_bias_get_type(void)
{
	static gsize static_g_enum_type_id;

	if (g_once_init_enter(&static_g_enum_type_id)) {
		static const GEnumValue values[] = {
			{GPIODGLIB_LINE_BIAS_AS_IS, "GPIODGLIB_LINE_BIAS_AS_IS", "as-is"},
			{GPIODGLIB_LINE_BIAS_UNKNOWN, "GPIODGLIB_LINE_BIAS_UNKNOWN", "unknown"},
			{GPIODGLIB_LINE_BIAS_DISABLED, "GPIODGLIB_LINE_BIAS_DISABLED", "disabled"},
			{GPIODGLIB_LINE_BIAS_PULL_UP, "GPIODGLIB_LINE_BIAS_PULL_UP", "pull-up"},
			{GPIODGLIB_LINE_BIAS_PULL_DOWN, "GPIODGLIB_LINE_BIAS_PULL_DOWN", "pull-down"},
			{ 0, NULL, NULL }
		};

		GType g_enum_type_id = g_enum_register_static(
				g_intern_static_string("GpiodglibLineBias"), values);

		g_once_init_leave (&static_g_enum_type_id, g_enum_type_id);
	}

	return static_g_enum_type_id;
}

GType gpiodglib_line_drive_get_type(void)
{
	static gsize static_g_enum_type_id;

	if (g_once_init_enter(&static_g_enum_type_id)) {
		static const GEnumValue values[] = {
			{GPIODGLIB_LINE_DRIVE_PUSH_PULL, "GPIODGLIB_LINE_DRIVE_PUSH_PULL", "push-pull"},
			{GPIODGLIB_LINE_DRIVE_OPEN_DRAIN, "GPIODGLIB_LINE_DRIVE_OPEN_DRAIN", "open-drain"},
			{GPIODGLIB_LINE_DRIVE_OPEN_SOURCE, "GPIODGLIB_LINE_DRIVE_OPEN_SOURCE", "open-source"},
			{ 0, NULL, NULL }
		};

		GType g_enum_type_id = g_enum_register_static(
				g_intern_static_string("GpiodglibLineDrive"), values);

		g_once_init_leave (&static_g_enum_type_id, g_enum_type_id);
	}

	return static_g_enum_type_id;
}

GType gpiodglib_line_clock_get_type(void)
{
	static gsize static_g_enum_type_id;

	if (g_once_init_enter(&static_g_enum_type_id)) {
		static const GEnumValue values[] = {
			{GPIODGLIB_LINE_CLOCK_MONOTONIC, "GPIODGLIB_LINE_CLOCK_MONOTONIC", "monotonic"},
			{GPIODGLIB_LINE_CLOCK_REALTIME, "GPIODGLIB_LINE_CLOCK_REALTIME", "realtime"},
			{GPIODGLIB_LINE_CLOCK_HTE, "GPIODGLIB_LINE_CLOCK_HTE", "hte"},
			{ 0, NULL, NULL }
		};

		GType g_enum_type_id = g_enum_register_static(
				g_intern_static_string("GpiodglibLineClock"), values);

		g_once_init_leave (&static_g_enum_type_id, g_enum_type_id);
	}

	return static_g_enum_type_id;
}

/* Generated data ends here */

